---
# AWS Step Function to stop RDS & Aurora databases after forced 7th-day start
# github.com/sqlxpert/step-stay-stopped-aws-rds-aurora GPLv3 Copyright Marcelin

ignore_checks:
  - W2510
  # W2510: Lambda Memory Size parameters should use MinValue, MaxValue or
  #        AllowedValues: See comment about "underlying APIs"
